Make sure that the Freemarker profiler is only applied on versions >= 2.3.23
where the Environment#getCurrentTemplate() method was introduced.
This prevents nasty IllegalAccessErrors and NoSuchMethodErrors.