Check if ServletContextInitializer is present in SpringBootWebPluginInitializer
This class was moved to a different package in Spring Boot 1.4 and the
old location was removed in Spring Boot 1.5.

So auto init for Spring Boot only works for Spring Boot 1.4+
This avoids a java.lang.NoClassDefFoundError:
org/springframework/boot/web/servlet/ServletContextInitializer
in Spring Boot 1.3 applications